import { pool } from "../configServices/dbConfig.js";
import camelize from "camelize";
import { bucket } from "../configServices/cloudStorageConfig.js";
import snakeize from "snakeize";
import stripNulls from "../utils/stripNulls.js";
export default (io, socket) => {
  const sendDmMessage = async (message, callback) => {
    console.log("received socket event sendDmMessage");

    //add senderUid and timestamp (messageUid is generated by db)
    //save message to db
    //send message to dmAccountUid

    // message.messageUid = "test32e6-c4f8-44d4-9408-cfb4f8499d01";
    // message.senderUid = socket.accountUid;
    // message.timestamp = Date.now();
    // io.to(message.receiverUid).emit("receiveMessage", message);
    // callback(message);
    return;
  };

  const deleteMessage = (messageId) => {
    //delete message in db?
    socket.emit("deleteMessage", messageId);
  };
  socket.on("sendDmMessage", sendDmMessage);
  socket.on("deleteMessage", deleteMessage);
};
