openapi: 3.0.0
info:
  version: "1"
  title: chefswap
  description: The API for chefswap
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/MATTHEWS13542/chefswap/1
  - url: http://localhost:3001/api/v1
    description: development
paths:
  /accounts:
    get:
      summary: Read profile data from accounts
      parameters:
        - in: query
          name: username
          description: username of account
          schema:
            type: string
            minLength: 3
            maxLength: 80
            pattern: '[^!*''();:@&=+$,/?%#[\]]{3,80}' #can't conatain any url reserved characters
        - in: query
          name: includeDistanceFrom
          description: distance from specified latitude/longitude to centre of account's circle will be added to response body
          explode: true
          style: deepObject
          schema: #if includeDistance exists, it must have both latitude and longitude
            oneOf:
              - type: object
                additionalProperties: false
                required:
                  - latitude
                  - longitude
                properties:
                  latitude:
                    type: number
                    format: float
                    minimum: -90
                    maximum: 90
                  longitude:
                    type: number
                    format: float
                    minimum: -180
                    maximum: 180
              - type: object #workaround to have optional param with required fields
                nullable: true
                additionalProperties: false
        - in: query
          name: minRating
          description: min rating of accounts
          schema:
            type: number
            format: float
            minimum: 1
            maximum: 5
        - in: query
          name: maxRating
          description: max rating of accounts
          schema:
            type: number
            format: float
            minimum: 1
            maximum: 5
        - in: query
          name: cuisinePreference
          description: cuisine preferences of accounts
          schema:
            type: array
            items:
              $ref: "#/components/schemas/CuisineType"
        - in: query
          name: cuisineSpeciality
          description: cuisineSpecialities of accounts
          schema:
            type: array
            items:
              $ref: "#/components/schemas/CuisineType"
        - in: query
          name: maxDistance
          description: max distance to account
          schema:
            type: integer
            format: int32
            minimum: 50
            maximum: 2000000000
        - in: query
          name: orderBy
          description: how to order results
          schema:
            type: string
            enum:
              - avgRatingAsc
              - avgRatingDesc
              - distanceAsc
              - distanceDesc
        - in: query
          name: key
          description: max item before first result of new query
          explode: true
          style: deepObject
          schema:
            oneOf:
              - type: object #no ordering (just order by uuidAsc)
                additionalProperties: false
                properties:
                  accountUid:
                    type: string
                    format: uuid
                    default: 00000000-0000-0000-0000-000000000000
              - type: object #ordering by distance
                additionalProperties: false
                properties:
                  accountUid:
                    type: string
                    format: uuid
                    default: 00000000-0000-0000-0000-000000000000
                  distance:
                    oneOf:
                      - type: integer
                        format: int32
              - type: object #ordering by rating
                additionalProperties: false
                properties:
                  accountUid:
                    type: string
                    format: uuid
                    default: 00000000-0000-0000-0000-000000000000
                  avgRating:
                    type: number
                    format: float
        - in: query
          name: limit
          description: number of records to retrieve
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 1000
            default: 20
      responses:
        200:
          description: Profile data from matching accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  required:
                    - profile
                  properties:
                    profile:
                      $ref: "#/components/schemas/AccountProfile"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
    post:
      summary: Create an account
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Account"
      responses:
        201:
          description: The account was successfully created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Account"
        400:
          description: The request body is poorly formated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
  /accounts/{accountUid}:
    parameters:
      - name: accountUid
        description: The uuid of an account
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Read an account. Returns all data in signed in as account and only profile data otherwise
      responses:
        200:
          description: The account corresponding to the provided uid. Includes only profile information unless authenticated with target account.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Account"
                  - $ref: "#/components/schemas/AccountProfile"
        400:
          description: accountUid is not a valid uuid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        404:
          description: No account found for the provided uid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: integer
  /accounts/{accountUid}/username:
    parameters:
      - name: accountUid
        description: The uuid of an account
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      summary: Read username of an account.
      responses:
        200:
          description: The username of the account corresponding to the provided uid.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Username"
        400:
          description: accountUid is not a valid uuid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        404:
          description: No account found for the provided uid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: integer
    put:
      summary: Update the username of an account.
      responses:
        200:
          description: The updated username of the account corresponding to the provided uid.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Username"
        400:
          description: accountUid is not a valid uuid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        401:
          description: client not signed in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        403:
          description: client signed in, but not as targetted account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        404:
          description: No account found for the provided uid
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        409:
          description: username taken
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Errors"
        500:
          description: Unexpected error
          content:
            application/json:
              schema:
                type: integer
  /session:
    post:
      summary: Update the username of an account.
      responses:
        200:
          description: The updated username of the account corresponding to the provided uid.
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Username"
components:
  schemas:
    Image:
      type: object
      description: representation of image
      required:
        - imageUid
        - accountUid
        - imageLink
        - imageName
        - timestamp
      properties:
        imageUid:
          readOnly: true
          type: string
          format: uuid
        accountUid:
          readOnly: true
          type: string
          format: uuid
        imageLink:
          readOnly: true
          allOf:
            - $ref: "#/components/schemas/ImageLink"
        imageName:
          type: string
        timestamp:
          readOnly: true
          type: string
          format: date-time
    ImageLink:
      type: string
      description: link to image in google cloud storage
      pattern: '^https:\/\/storage\.googleapis\.com\/.+$'
    CuisineType:
      type: string
      enum:
        - Indian
        - Italian
        - Greek
    AccountProfile:
      type: object
      description: profile data available without authentication
      required:
        - accountUid
        - username
        - bio
        - circle
        - numRatings
        - createTime
        - updateTime
        - images
        - cuisinePreferences
        - cuisineSpecialities
      properties:
        accountUid:
          readOnly: true
          type: string
          format: uuid
        username:
          $ref: "#/components/schemas/Username"
        bio:
          type: string
          maxLength: 500
        circle:
          $ref: "#/components/schemas/Circle"
        pfpLink:
          readOnly: true
          allOf:
            - $ref: "#/components/schemas/ImageLink"
        avgRating:
          readOnly: true
          type: number
          minimum: 1
          maximum: 5
        numRatings:
          readOnly: true
          type: integer
          minimum: 0
        createTime:
          readOnly: true
          type: string
          format: date-time
        updateTime:
          readOnly: true
          type: string
          format: date-time
        images:
          readOnly: true
          type: array
          items:
            $ref: "#/components/schemas/Image"
        cuisinePreferences:
          readOnly: true
          type: array
          items:
            $ref: "#/components/schemas/CuisineType"
        cuisineSpecialities:
          readOnly: true
          type: array
          items:
            $ref: "#/components/schemas/CuisineType"
    Account:
      type: object
      required:
        - profile
        - email
        - password
        - address
      properties:
        profile:
          $ref: "#/components/schemas/AccountProfile"
        email:
          type: string
          format: email
          maxLength: 80
        password:
          writeOnly: true
          allOf:
            - $ref: "#/components/schemas/Password"
        address:
          $ref: "#/components/schemas/Address"
    Address:
      type: object
      required:
        - addressUid
        - address1
        - city
        - province
        - postalCode
      properties:
        addressUid:
          readOnly: true
          type: string
          format: uuid
        address1:
          type: string
          maxLength: 80
        address2:
          type: string
          maxLength: 80
        address3:
          type: string
          maxLength: 80
        city:
          type: string
          maxLength: 35
        province:
          type: string
          enum:
            - Ontario
            - Quebec
            - British Columbia
            - Alberta
            - Manitoba
            - Saskatchewan
            - Nova Scotia
            - New Brusnwick
            - Newfoundland and Labrador
            - Prince Edward Island
            - Northwest Territories
            - Yukon
            - Nunavut
        postalCode:
          type: string
          pattern: '^[ABCEGHJKLMNPRSTVXY]\d[ABCEGHJ-NPRSTV-Z]\d[ABCEGHJ-NPRSTV-Z]\d$'
    Circle:
      type: object
      required:
        - circleUid
        - radius
        - latitude
        - longitude
      properties:
        circleUid:
          readOnly: true
          type: string
          format: uuid
        radius:
          type: integer
          minimum: 50
          maximum: 3000
        latitude:
          readOnly: true
          type: number
          format: float
        longitude:
          readOnly: true
          type: number
          format: float
    Username:
      type: string
      minLength: 3
      maxLength: 80
      pattern: '[^!*''();:@&=+$,/?%#[\]]{3,80}' #can't conatain any url reserved characters
    Password:
      type: string
      minLength: 8
      maxLength: 50
      pattern: '^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,50}$' #must contain lowercase, uppercase, number
    Errors:
      type: array
      items:
        $ref: "#/components/schemas/Error"
    Error:
      type: object
      required:
        - path
        - message
        - detail
      properties:
        path:
          type: string
        message:
          type: string
        detail:
          type: string
  securitySchemes:
    ApiKey:
      type: apiKey
      in: header
      name: X-Api-Key
security:
  - ApiKey: [thisisanapikey]
